### ISSUE TITLE
"Convert an array-like object to array" ... with spread operator

### ISSUE THREAD

**Issue by geoffreydhuyvetters** [reindexio/youmightnotneedunderscore#12]
I think 

```
[...arguments]
```

is also a possible solution for _.toArray()

works with `document.querySelectorAll` for example

```
[...document.querySelectorAll('a')].forEach(createLink);
```

**Comment by fson** [comment]
I'm aware of this, but I wonder if `Array.from` is easier to understand? On the other hand, there is a bunch of examples using `[...a]` already, so I guess we might as well use it here too.

**Comment by fson** [comment]
Added in https://github.com/reindexio/youmightnotneedunderscore/commit/a6634c8416da90463d3ce15b637c2e424eabafa8.

**Comment by styfle** [comment]
@fson I agree that `Array.from` is easier to understand because it explicitly tells you what its doing.

If someone came across `Array.from` in code and didn't know the purpose, they could google it and find [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from) which says:

> creates a new Array instance from an array-like or iterable object

This is very similar to what the README says:

> Convert an array-like object to array

Conversely, a developer who is unaware of the [Spread Syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) would have a difficult time googling it and would find a convoluted description:

> allows an iterable such as an array expression to be expanded in places where zero or more arguments (for function calls) or elements (for array literals) are expected, or an object expression to be expanded in places where zero or more key-value pairs (for object literals) are expected

I'm not sure how different the browser support would be since both are ES2015. Perhaps both solutions should be presented?
